# -*- coding: utf-8 -*-
"""lab_04

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MC5vJAdVoxXEzFV-NvzQr8s6OpL4HWow
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

document1='the man went out for a walk'
document2='the children sat around the fire'

docs=[document1,document2]

vecs=TfidfVectorizer()

tfidf_mat=vecs.fit_transform(docs)
tfidf_mat

tfidf_mat.toarray()

cs=cosine_similarity(tfidf_mat[0],tfidf_mat[1])
cs

cs[0][0]